name: tacos

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  - module01-docker-start

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Installing Node.js'

  - script: |
      npm install
      npm run build -- --prod
    displayName: 'Running npm install and build'
  - script: docker build -t $(dockerId)/$(imageName)  .
  - script: docker login -u $(user) -p $(password) angularmixtacos.azurecr.io
  - script: docker push $(dockerId)/$(imageName)